Replace Rapptz/jsonpp with nlohmann/json
clang++ -O3 -std=c++14 -pedantic -Wall -Wextra -pipe  -isystemext/whereami-cpp/include -isystemext/totalcmd-wcx-api -isystemext/jsonpp -isystemext/inih -isystemout/build/zstd/include -DTOTALCMD_ZSTD_VERSION='"0.2.0"' -DWHEREAMI_CPP_VERSION='"1.1.1"' -DJSONPP_VERSION='"e855ca8"' -DINIH_VERSION='"58"' -DZSTD_STATIC_LINKING_ONLY -c -oout/build/obj/config.o src/config.cpp
In file included from src/config.cpp:27:
In file included from ext/jsonpp/jsonpp/parser.hpp:26:
ext/jsonpp/jsonpp/value.hpp:455:17: error: friend declaration specifying a default argument must be the only declaration
  455 | inline OStream& dump(OStream& out, const value& val, format_options opt);
      |                 ^
ext/jsonpp/jsonpp/value.hpp:409:21: note: previous declaration is here
  409 |     friend OStream& dump(OStream& out, const value& val, format_options opt = {}) {
      |                     ^
1 error generated.
make: *** [Makefile:65: out/build/obj/config.o] Error 1
make: Target 'all' not remade because of errors.

In file included from ext/jsonpp/jsonpp/parser.hpp:26,
                 from src/config.cpp:27:
ext/jsonpp/jsonpp/value.hpp:455:17: error: friend declaration of 'OStream& json::dump(OStream&, const value&, format_options)' specifies default arguments and isn't the only declaration [-fpermissive]
  455 | inline OStream& dump(OStream& out, const value& val, format_options opt);
      |                 ^~~~
ext/jsonpp/jsonpp/value.hpp:409:21: note: previous declaration of 'OStream& json::dump(OStream&, const value&, format_options)'
  409 |     friend OStream& dump(OStream& out, const value& val, format_options opt = {}) {
      |                     ^~~~
make: *** [Makefile:65: out/build/obj/config.o] Error 1